create table GENRES
(
    GENRE_ID   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    GENRE_NAME CHARACTER VARYING(255) not null,
    constraint GENRE_PK
        primary key (GENRE_ID)
);

create table MPA
(
    MPA_ID   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    MPA_NAME CHARACTER VARYING(255) not null,
    constraint MPA_PK
        primary key (MPA_ID)
);

create table USERS
(
    USER_ID   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    EMAIL     CHARACTER VARYING(255) not null
        unique,
    LOGIN     CHARACTER VARYING(255) not null
        unique,
    USER_NAME CHARACTER VARYING(255) not null,
    BIRTHDAY  DATE                   not null,
    constraint USERS_PK
        primary key (USER_ID)
);

create table FILMS
(
    FILM_ID      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    FILM_NAME    CHARACTER VARYING(255) not null,
    DESCRIPTION  CHARACTER VARYING(255) not null,
    MPA_ID       CHARACTER VARYING(255) not null,
    RELEASE_DATE DATE                   not null,
    DURATION     INTEGER                not null,
    RATE         INTEGER                not null,
    constraint FILMS_PK
        primary key (FILM_ID),
    constraint FILMS_MPA_MPA_ID_FK
        foreign key (MPA_ID) references MPA
);

create table FILMS_GENRES
(
    FILM_ID  INTEGER not null,
    GENRE_ID INTEGER not null,
    constraint FILMS_GENRES_PK
        primary key (FILM_ID, GENRE_ID),
    constraint "FILMS_GENRES_FILMS_null_fk"
        foreign key (FILM_ID) references FILMS,
    constraint "FILMS_GENRES_GENRES_null_fk"
        foreign key (GENRE_ID) references GENRES
);

create table FILMS_LIKES
(
    FILM_ID  INTEGER not null,
    USER_ID INTEGER not null,
    constraint FILMS_LIKES_PK
        primary key (FILM_ID, USER_ID),
    constraint "FILMS_LIKES_FILMS_null_fk"
        foreign key (FILM_ID) references FILMS,
    constraint "FILMS_LIKES_USERS_null_fk"
        foreign key (USER_ID) references USERS
);

create table FRIENDS
(
    FRIEND_ID  INTEGER not null,
    USER_ID INTEGER not null,
    constraint FRIENDS_PK
        primary key (FRIEND_ID, USER_ID),
    constraint "FRIENDS_FRIENDS_null_fk"
        foreign key (FRIEND_ID) references USERS,
    constraint "FRIENDS_USERS_null_fk"
        foreign key (USER_ID) references USERS
);