create table IF NOT EXISTS USERS
(
    USER_ID   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    EMAIL     CHARACTER VARYING(255) not null,
    LOGIN     CHARACTER VARYING(255) not null,
    USER_NAME CHARACTER VARYING(255) not null,
    BIRTHDAY  DATE                   not null,
    constraint USERS_PK
        primary key (USER_ID)
);
create table IF NOT EXISTS GENRE
(
    GENRE_ID   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    GENRE_NAME CHARACTER VARYING(255) not null,
    constraint GENRE_PK
        primary key (GENRE_ID)
);
create table IF NOT EXISTS MPA
(
    MPA_ID   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    MPA_NAME CHARACTER VARYING(255) not null,
    constraint MPA_PK
        primary key (MPA_ID)
);
create table IF NOT EXISTS FILMS
(
    FILM_ID      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    FILM_NAME    CHARACTER VARYING(255) not null,
    DESCRIPTION  CHARACTER VARYING(255) not null,
    GENRE_ID     CHARACTER VARYING(255) not null,
    MPA_ID       CHARACTER VARYING(255) not null,
    RELEASE_DATE DATE                   not null,
    DURATION     INTEGER                not null,
    RATE         INTEGER                not null,
    USER_ID      INTEGER,
    constraint FILMS_PK
        primary key (FILM_ID),
    constraint FILMS_GENRE_GENRE_ID_FK
        foreign key (GENRE_ID) references GENRE,
    constraint FILMS_MPA_MPA_ID_FK
        foreign key (MPA_ID) references MPA,
    constraint FILMS_USERS_USER_ID_FK
        foreign key (USER_ID) references USERS
);